### ISSUE TITLE
Unity project does not initialize properly on clone of repository

### ISSUE THREAD

**Issue by jcollard** [CaptainCoderOrg/DungeonCrawlerJam2024#86]
When the project is cloned, it is missing TextMeshPro. Additionally, all of the associated script references cannot be found and need to be rewired.

**Comment by unitycoder** [comment]
seems to miss "Packages/", "ProjectSettings/" folders in github? (Or is that on purpose)

(those folders are usually added to git, contains TextMeshPro and other packages and project/platform settings)
